### ISSUE TITLE
[webpack-cli] Promise rejection: TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by jefflung** [weimingw/weiming-demystify-apple#1]
I got below error message after I ran npm start, could you help me? Thanks.
```
[webpack-cli] Promise rejection: TypeError: The 'compilation' argument must be an instance of Compilation
[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (C:\Users\nosy_\desktop\learn\weiming-demystify-apple-main\node_modules\webpack\lib\NormalModule.js:171:10)
    at C:\Users\nosy_\desktop\learn\weiming-demystify-apple-main\node_modules\webpack\lib\HotModuleReplacementPlugin.js:571:18
    at Hook.eval [as call] (eval at create (C:\Users\nosy_\Desktop\Learn\weiming-demystify-apple-main\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Users\nosy_\Desktop\Learn\weiming-demystify-apple-main\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Users\nosy_\Desktop\Learn\weiming-demystify-apple-main\node_modules\webpack\lib\Compiler.js:943:26)
    at C:\Users\nosy_\Desktop\Learn\weiming-demystify-apple-main\node_modules\webpack\lib\Compiler.js:984:29
    at Hook.eval [as callAsync] (eval at create (C:\Users\nosy_\Desktop\Learn\weiming-demystify-apple-main\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\nosy_\Desktop\Learn\weiming-demystify-apple-main\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (C:\Users\nosy_\Desktop\Learn\weiming-demystify-apple-main\node_modules\webpack\lib\Compiler.js:979:28)
    at C:\Users\nosy_\Desktop\Learn\weiming-demystify-apple-main\node_modules\webpack\lib\Watching.js:113:19
```

**Comment by huni1023** [comment]
are you installed before 'npm start'?

'npm install' should be preceded
